// Generated by CoffeeScript 1.6.3
(function() {
  window.App = Ember.Application.create();

  App.IndexController = Ember.ObjectController.extend({
    orginText: "",
    keyWordStr: "",
    keyWordArr: (function() {
      var arr = this.get("keyWordStr").split("\n");
      arr.forEach(function(value, index) {
        arr[index] = arr[index].trim().toLowerCase().replace(/[ \t]+/g, " ");
      });
      return arr;
    }).property("keyWordStr"),
    replacedText: (function() {
      var str = this.get("orginText").trim();      
      return str.replace(/[ \t]+/g, " ");
    }).property("orginText"),
    searchResult: (function() {
      var replacedText, result;
      result = [];
      replacedText = this.get("replacedText");
      this.get("keyWordArr").forEach(function(value) {
        var word, count;
        word = value;
        count = replacedText.toLowerCase().split(word).length - 1;
        if (count > 0) {
          result.push({
            word: value,
            count: count
          });
        }
      });
      return result;
    }).property("replacedText", "keyWordArr"),
    highlightText: (function() {
      return $("<p>" + (_.escape(this.get("replacedText"))) + "</p>").highlight(this.get("keyWordArr")).html();
    }).property("replacedText", "keyWordArr")
  });

}).call(this);
